### ISSUE TITLE
error during pgn parsing

### ISSUE THREAD

**Issue by raf-lii** [tinwaninja/Catur#6]
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\pgn.py", line 1555, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\pgn.py", line 938, in parse_san
    return board.parse_san(san)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\__init__.py", line 2832, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'Kc6' in rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
54 fxe5

**Comment by tinwaninja** [comment]
make sure the upper and lower case in account.txt is the same as the username that appears in the chat

**Comment by raf-lii** [comment]
> make sure the upper and lower case in account.txt is the same as the username that appears in the chat

yes they are already same and i got that error

**Comment by mafiavc** [comment]
> make sure the upper and lower case in account.txt is the same as the username that appears in the chat

why you close the issue, that solves nothing I also have this problem:(
