### ISSUE TITLE
error

### ISSUE THREAD

**Issue by erxson** [tinwaninja/Catur#7]
Log:

C:\Users\pro11\Desktop\Catur-main>python catur.py
Menunggu pertandingan dimulai  0
Menunggu pertandingan dimulai  1
Menunggu pertandingan dimulai  2
Menunggu pertandingan dimulai  3
Menunggu pertandingan dimulai  4
Menunggu pertandingan dimulai  5
Menunggu pertandingan dimulai  6
Menunggu pertandingan dimulai  7
Menunggu pertandingan dimulai  8
Menunggu pertandingan dimulai  0
НОВАЯ ПАРТИЯ
erhhh07 (553) против maddmark (500) (5 мин)
победа +100 / ничья -18 / проигрыш -136
mode kecepatan permainan: blitz
erhhh07 bermain sebagai putih
1 e4
2 e6
delay 0.2474036346476528  detik
3 d4
4 d5
delay 0.10227821921072358  detik
5 Кc3
6 c6
delay 0.20726407449094675  detik
7 e5
8 f6
delay 0.10661523335252664  detik
9 Сd3
error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\pro11\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\pgn.py", line 1555, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\pro11\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\pgn.py", line 938, in parse_san
    return board.parse_san(san)
  File "C:\Users\pro11\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\__init__.py", line 2832, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'd3' in rnbqkbnr/pp4pp/2p1pp2/3pP3/3P4/2P5/PP3PPP/RNBQKBNR w KQkq - 0 5
10 fxe5
error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\pro11\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\pgn.py", line 1555, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\pro11\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\pgn.py", line 938, in parse_san
    return board.parse_san(san)
  File "C:\Users\pro11\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\__init__.py", line 2832, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'd3' in rnbqkbnr/pp4pp/2p1pp2/3pP3/3P4/2P5/PP3PPP/RNBQKBNR w KQkq - 0 5
delay 0.15222680058790133  detik

**Comment by erxson** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/50082485/114313055-9ad53700-9afd-11eb-99fb-5c93a056eb76.png)
